name: Validate HACS
on:
  push:
  pull_request:
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: HACS Action
        uses: hacs/action@main
        with:
          CATEGORY: integration